# Generated by Django 5.1.7 on 2025-04-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_animeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeentry',
            name='episodes_watched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='is_rewatching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
